### ISSUE TITLE
Django-phased with i18n trans tag

### ISSUE THREAD

**Issue by timc3** [codysoyland/django-phased#1] opened 2010-10-07 22:16 UTC
Probably a known problem, but I couldn't see it in the docs anywhere.

If you try and use {% phased %} and the trans tag you get a TemplateSyntaxError: Invalid block tag: 'trans' error message.

Is there away around this?

**Comment by codysoyland** [comment] 2010-10-08 02:28
This isn't noted in the documentation, but it is a known issue. The problem is that the loaded template libraries are not re-loaded during the second-phase rendering, so in order to use them, you must re-load them manually. The solution is the put {% load i18n %} after the {% phased %} tag so it is loaded during the second phase. I will try to give the docs some love soon, so I will keep the ticket open until I've clearly documented this gotcha.

**Comment by jezdez** [comment] 2010-12-06 23:05
Fixed in e0552688432cbf59fa293ed64df4f668db1b7e62 \o/

**Closed as completed by jezdez** 2010-12-06 23:05 UTC

**Comment by philipn** [comment] 2014-08-17 14:35
This seems to still be an issue, so should this be re-opened?  Or perhaps the issue should be documented?
